# Generated by Django 6.0.1 on 2026-01-28 22:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='percentual_comissao',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Percentual de comissão sobre receitas (padrão: 20%)', max_digits=5),
        ),
    ]
