# Generated by Django 5.2.1 on 2025-05-24 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='formato_cobranca',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='percentual_exito',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='valor_mensal',
        ),
        migrations.CreateModel(
            name='FormaCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(choices=[('M', 'Valor Mensal'), ('E', 'Êxito')], max_length=1)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentual_exito', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_cobranca', to='core.cliente')),
            ],
        ),
    ]
