# Generated by Django 6.0.1 on 2026-01-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_percentual_comissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabancaria',
            name='saldo_inicial',
        ),
    ]
