# Generated by Django 6.0.1 on 2026-01-30 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_contabancaria_saldo_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('F', 'Despesa Fixa'), ('V', 'Despesa Variável')], default='F', max_length=1)),
                ('data_inicio', models.DateField(help_text='Data da primeira ocorrência')),
                ('data_fim', models.DateField(blank=True, help_text='Data da última ocorrência (opcional)', null=True)),
                ('dia_vencimento', models.IntegerField(default=1, help_text='Dia do mês para vencimento (1-31)')),
                ('status', models.CharField(choices=[('A', 'Ativa'), ('P', 'Pausada')], default='A', max_length=1)),
                ('ultimo_mes_gerado', models.DateField(blank=True, help_text='Último mês em que despesas foram geradas', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('responsavel', models.ForeignKey(help_text='Favorecido da despesa', on_delete=django.db.models.deletion.PROTECT, to='core.funcionario')),
            ],
            options={
                'verbose_name': 'Despesa Recorrente',
                'verbose_name_plural': 'Despesas Recorrentes',
                'ordering': ['nome'],
            },
        ),
    ]
