# Generated by Django 6.0.1 on 2026-01-31 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_receitarecorrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitarecorrente',
            name='comissionado',
            field=models.ForeignKey(blank=True, help_text='Funcionário ou Parceiro que receberá comissão', limit_choices_to={'tipo__in': ['F', 'P']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funcionario'),
        ),
        migrations.AddField(
            model_name='receitarecorrente',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('P', 'Pix'), ('B', 'Boleto')], max_length=1, null=True),
        ),
    ]
