# Generated by Django 5.2.1 on 2026-01-16 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cliente_cpf_alter_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='receita_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_comissao', to='core.receita'),
        ),
    ]
