# Generated by Django 6.0.1 on 2026-01-31 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_receitarecorrente_comissionado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitarecorrente',
            name='ultimo_mes_gerado',
        ),
    ]
