# Generated by Django 6.0.1 on 2026-01-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_receitarecorrente_ultimo_mes_gerado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesarecorrente',
            name='ultimo_mes_gerado',
        ),
        migrations.AddField(
            model_name='despesarecorrente',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('P', 'Pix'), ('B', 'Boleto')], max_length=1, null=True),
        ),
    ]
