# Generated by Django on 2026-02-03

from django.db import migrations
from django.db.models import Count


def fix_duplicate_names(apps, schema_editor):
    """
    Renomeia registros duplicados adicionando um sufixo numérico.
    """
    Cliente = apps.get_model('core', 'Cliente')
    Funcionario = apps.get_model('core', 'Funcionario')

    # Fix duplicated Clientes
    cliente_duplicates = (
        Cliente.objects.values('nome')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )

    for dup in cliente_duplicates:
        nome = dup['nome']
        clientes = Cliente.objects.filter(nome=nome).order_by('id')

        # Keep the first one with original name, rename the rest
        for idx, cliente in enumerate(clientes[1:], start=1):
            cliente.nome = f"{nome} ({idx})"
            cliente.save()

    # Fix duplicated Funcionarios
    func_duplicates = (
        Funcionario.objects.values('nome')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )

    for dup in func_duplicates:
        nome = dup['nome']
        funcionarios = Funcionario.objects.filter(nome=nome).order_by('id')

        # Keep the first one with original name, rename the rest
        for idx, funcionario in enumerate(funcionarios[1:], start=1):
            funcionario.nome = f"{nome} ({idx})"
            funcionario.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_funcionario_cpf_alter_funcionario_email'),
    ]

    operations = [
        migrations.RunPython(fix_duplicate_names, migrations.RunPython.noop),
    ]
