# Generated by Django 6.0.1 on 2026-02-04 16:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_cliente_nome_alter_funcionario_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_liquidado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('P', 'Parcial'), ('L', 'Liquidado')], default='A', max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente relacionado ao passivo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passivos', to='core.cliente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('funcionario', models.ForeignKey(blank=True, help_text='Funcionário/Fornecedor/Parceiro relacionado ao passivo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passivos', to='core.funcionario')),
            ],
            options={
                'verbose_name': 'Passivo',
                'verbose_name_plural': 'Passivos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Quanto deste pagamento foi alocado para esta conta', max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('despesa', models.ForeignKey(blank=True, help_text='Despesa para a qual este pagamento foi alocado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='core.despesa')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.payment')),
                ('receita', models.ForeignKey(blank=True, help_text='Receita para a qual este pagamento foi alocado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='core.receita')),
                ('passivo', models.ForeignKey(blank=True, help_text='Passivo para o qual este pagamento foi alocado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='core.passivo')),
            ],
            options={
                'verbose_name': 'Alocação',
                'verbose_name_plural': 'Alocações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
