# Generated by Django 6.0.1 on 2026-02-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_passivo_allocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-data_pagamento', '-criado_em'], 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='despesa',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receita',
        ),
        migrations.AddField(
            model_name='payment',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], default=1, help_text='Tipo de movimentação: Entrada (recebimento) ou Saída (pagamento)', max_length=1),
            preserve_default=False,
        ),
    ]
