# Generated by Django 6.0.1 on 2026-02-04 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_payment_options_remove_payment_despesa_and_more'),
    ]

    operations = [
        # Renomear modelo Passivo para Custodia
        migrations.RenameModel(
            old_name='Passivo',
            new_name='Custodia',
        ),

        # Adicionar campo tipo ao modelo Custodia
        migrations.AddField(
            model_name='custodia',
            name='tipo',
            field=models.CharField(
                choices=[('P', 'Passivo'), ('A', 'Ativo')],
                default='P',
                max_length=1
            ),
        ),

        # Renomear campo passivo para custodia em Allocation
        migrations.RenameField(
            model_name='allocation',
            old_name='passivo',
            new_name='custodia',
        ),

        # Atualizar relacionamentos (related_name) em Cliente
        migrations.AlterField(
            model_name='custodia',
            name='cliente',
            field=models.ForeignKey(
                blank=True,
                help_text='Cliente relacionado à custódia',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='custodias',
                to='core.cliente'
            ),
        ),

        # Atualizar relacionamentos (related_name) em Funcionario
        migrations.AlterField(
            model_name='custodia',
            name='funcionario',
            field=models.ForeignKey(
                blank=True,
                help_text='Funcionário/Fornecedor/Parceiro relacionado à custódia',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='custodias',
                to='core.funcionario'
            ),
        ),
    ]
