# Generated by Django 6.0.1 on 2026-02-04 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20260204_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custodia',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Custódia', 'verbose_name_plural': 'Custódias'},
        ),
        migrations.AlterField(
            model_name='allocation',
            name='custodia',
            field=models.ForeignKey(blank=True, help_text='Custódia para a qual este pagamento foi alocado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='core.custodia'),
        ),
        migrations.AlterModelTable(
            name='custodia',
            table='core_passivo',
        ),
    ]
