# Generated by Django 6.0.1 on 2026-02-06 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_custodia_options_alter_allocation_custodia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_transferencia', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('M', 'Mismatch'), ('C', 'Completo')], default='P', max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('from_bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='core.contabancaria', verbose_name='Banco de Origem')),
                ('to_bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='core.contabancaria', verbose_name='Banco de Destino')),
            ],
            options={
                'verbose_name': 'Transferência',
                'verbose_name_plural': 'Transferências',
                'ordering': ['-data_transferencia', '-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='allocation',
            name='transfer',
            field=models.ForeignKey(blank=True, help_text='Transferência para a qual este pagamento foi alocado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='core.transfer'),
        ),
    ]
