# Generated by Django 6.0.1 on 2026-02-06 14:47

import django.db.models.deletion
from django.db import migrations, models


def migrate_comissionado_data(apps, schema_editor):
    """
    Migra dados de comissionado de Receita para Cliente.
    Pega o comissionado mais recente de cada cliente.
    """
    Cliente = apps.get_model('core', 'Cliente')
    Receita = apps.get_model('core', 'Receita')

    for cliente in Cliente.objects.all():
        # Busca a receita mais recente com comissionado
        receita = Receita.objects.filter(
            cliente=cliente,
            comissionado__isnull=False
        ).order_by('-data_vencimento').first()

        if receita:
            cliente.comissionado = receita.comissionado
            cliente.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_transfer_allocation_transfer'),
    ]

    operations = [
        # 1. Adicionar campo em Cliente primeiro
        migrations.AddField(
            model_name='cliente',
            name='comissionado',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo__in': ['F', 'P']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funcionario', verbose_name='Funcionário Comissionado'),
        ),
        # 2. Migrar dados
        migrations.RunPython(migrate_comissionado_data, reverse_code=migrations.RunPython.noop),
        # 3. Remover campos antigos
        migrations.RemoveField(
            model_name='receita',
            name='comissionado',
        ),
        migrations.RemoveField(
            model_name='receitarecorrente',
            name='comissionado',
        ),
    ]
