# Generated by Django 6.0.1 on 2026-02-10 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_move_comissionado_to_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='comissionado',
            field=models.ForeignKey(blank=True, help_text='Substitui o comissionado padrão do cliente para esta receita', limit_choices_to={'tipo__in': ['F', 'P']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funcionario', verbose_name='Comissionado Específico'),
        ),
        migrations.AddField(
            model_name='receitarecorrente',
            name='comissionado',
            field=models.ForeignKey(blank=True, help_text='Substitui o comissionado padrão do cliente para esta receita recorrente', limit_choices_to={'tipo__in': ['F', 'P']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funcionario', verbose_name='Comissionado Específico'),
        ),
    ]
