# Generated by Django 6.0.1 on 2026-02-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_comissionado_to_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='percentual_comissao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de comissão específico para esta receita (sobrescreve o padrão da empresa)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='receitarecorrente',
            name='percentual_comissao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de comissão específico para esta receita recorrente (sobrescreve o padrão da empresa)', max_digits=5, null=True),
        ),
    ]
