# Generated by Django 6.0.1 on 2026-02-10 18:39

import django.db.models.deletion
from django.db import migrations, models
from decimal import Decimal


def migrate_cliente_comissionado(apps, schema_editor):
    """Migra Cliente.comissionado para ClienteComissao usando o percentual da company."""
    Cliente = apps.get_model('core', 'Cliente')
    ClienteComissao = apps.get_model('core', 'ClienteComissao')

    for cliente in Cliente.objects.filter(comissionado__isnull=False).select_related('comissionado', 'company'):
        percentual = cliente.company.percentual_comissao or Decimal('20.00')
        ClienteComissao.objects.get_or_create(
            cliente=cliente,
            funcionario=cliente.comissionado,
            defaults={'percentual': percentual}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_percentual_comissao_to_receita'),
    ]

    operations = [
        # 1. Criar novos modelos primeiro
        migrations.CreateModel(
            name='ClienteComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Percentual de comissão (%)', max_digits=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='core.cliente')),
                ('funcionario', models.ForeignKey(limit_choices_to={'tipo__in': ['F', 'P']}, on_delete=django.db.models.deletion.CASCADE, to='core.funcionario', verbose_name='Comissionado')),
            ],
            options={
                'verbose_name': 'Comissão do Cliente',
                'verbose_name_plural': 'Comissões do Cliente',
                'unique_together': {('cliente', 'funcionario')},
            },
        ),
        migrations.CreateModel(
            name='ReceitaComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Percentual de comissão (%)', max_digits=5)),
                ('funcionario', models.ForeignKey(limit_choices_to={'tipo__in': ['F', 'P']}, on_delete=django.db.models.deletion.CASCADE, to='core.funcionario', verbose_name='Comissionado')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='core.receita')),
            ],
            options={
                'verbose_name': 'Comissão da Receita',
                'verbose_name_plural': 'Comissões da Receita',
                'unique_together': {('receita', 'funcionario')},
            },
        ),
        migrations.CreateModel(
            name='ReceitaRecorrenteComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Percentual de comissão (%)', max_digits=5)),
                ('funcionario', models.ForeignKey(limit_choices_to={'tipo__in': ['F', 'P']}, on_delete=django.db.models.deletion.CASCADE, to='core.funcionario', verbose_name='Comissionado')),
                ('receita_recorrente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='core.receitarecorrente')),
            ],
            options={
                'verbose_name': 'Comissão da Receita Recorrente',
                'verbose_name_plural': 'Comissões da Receita Recorrente',
                'unique_together': {('receita_recorrente', 'funcionario')},
            },
        ),
        # 2. Migrar dados de Cliente.comissionado para ClienteComissao
        migrations.RunPython(migrate_cliente_comissionado, migrations.RunPython.noop),
        # 3. Remover campos antigos
        migrations.RemoveField(
            model_name='cliente',
            name='comissionado',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='comissionado',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='percentual_comissao',
        ),
        migrations.RemoveField(
            model_name='receitarecorrente',
            name='comissionado',
        ),
        migrations.RemoveField(
            model_name='receitarecorrente',
            name='percentual_comissao',
        ),
    ]
