# Generated by Django 6.0.1 on 2026-02-12 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_refactor_comissoes_to_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preco_anual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('asaas_billing_type', models.CharField(default='CREDIT_CARD', max_length=20)),
                ('max_usuarios', models.IntegerField(default=1)),
                ('features', models.JSONField(default=list)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plano de Assinatura',
                'verbose_name_plural': 'Planos de Assinatura',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('asaas_subscription_id', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Webhook',
                'ordering': ['-recebido_em'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(choices=[('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=10)),
                ('trial_inicio', models.DateTimeField(auto_now_add=True)),
                ('trial_fim', models.DateTimeField()),
                ('asaas_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('asaas_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('trial', 'Período de Teste'), ('active', 'Ativa'), ('overdue', 'Em Atraso'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='trial', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='core.company')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.planoassinatura')),
            ],
            options={
                'verbose_name': 'Assinatura da Empresa',
                'verbose_name_plural': 'Assinaturas das Empresas',
            },
        ),
    ]
