# Generated by Django 6.0.1 on 2026-02-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_update_precos_planos'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoassinatura',
            name='tem_trial',
            field=models.BooleanField(default=False),
        ),
    ]
