# Generated by Django 6.0.1 on 2026-02-13 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_set_essencial_tem_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturaempresa',
            name='pending_ciclo',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assinaturaempresa',
            name='pending_plano',
            field=models.ForeignKey(blank=True, help_text='Plano selecionado mas ainda não pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_pendentes', to='core.planoassinatura'),
        ),
    ]
