# Generated by Django 6.0.1 on 2026-02-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_proxima_cobranca_assinaturaempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturaempresa',
            name='asaas_subscription_ids_anteriores',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
