# Generated by Django 6.0.1 on 2026-02-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_asaas_subscription_ids_anteriores'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturaempresa',
            name='card_brand',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='assinaturaempresa',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
