# Generated by Django 6.0.1 on 2026-02-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_card_info_assinaturaempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturaempresa',
            name='card_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
