# Generated by Django 6.0.1 on 2026-02-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_card_token_assinaturaempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='asaas_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assinaturaempresa',
            name='status',
            field=models.CharField(choices=[('trial', 'Período de Teste'), ('active', 'Ativa'), ('overdue', 'Em Atraso'), ('payment_failed', 'Pagamento Recusado'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='trial', max_length=20),
        ),
    ]
