# Generated by Django 6.0.1 on 2026-02-15 19:28

from django.db import migrations


def backfill_email_verified(apps, schema_editor):
    CustomUser = apps.get_model('core', 'CustomUser')
    CustomUser.objects.all().update(is_email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_is_email_verified'),
    ]

    operations = [
        migrations.RunPython(backfill_email_verified, migrations.RunPython.noop),
    ]
